/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as publicPublicIndexRouteImport } from './routes/(public)/_public/index'

const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicIndexRoute = publicPublicIndexRouteImport.update({
  id: '/(public)/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/onboarding/': typeof OnboardingIndexRoute
  '/': typeof publicPublicIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingIndexRoute
  '/': typeof publicPublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/onboarding/': typeof OnboardingIndexRoute
  '/(public)/_public/': typeof publicPublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/onboarding/' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/onboarding' | '/'
  id: '__root__' | '/onboarding/' | '/(public)/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  publicPublicIndexRoute: typeof publicPublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_public/': {
      id: '/(public)/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
  publicPublicIndexRoute: publicPublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
